// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/ea054545eeb61cf7019133a3398d5e79cd5745ce/moment/moment.d.ts
declare var moment: moment.MomentStatic;